"""initial

Revision ID: 2222941912de
Revises: 93464c21768f
Create Date: 2025-12-12 10:54:02.341982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2222941912de'
down_revision: Union[str, Sequence[str], None] = '93464c21768f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nodes_id'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_ambiguities_id'), table_name='ambiguities')
    op.drop_table('ambiguities')
    op.drop_index(op.f('ix_graphs_id'), table_name='graphs')
    op.drop_table('graphs')
    op.drop_index(op.f('ix_edges_id'), table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('notes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='notes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('graph_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('from_node_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_node_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('relation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['from_node_id'], ['nodes.id'], name=op.f('edges_from_node_id_fkey')),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.id'], name=op.f('edges_graph_id_fkey')),
    sa.ForeignKeyConstraint(['to_node_id'], ['nodes.id'], name=op.f('edges_to_node_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('edges_pkey'))
    )
    op.create_index(op.f('ix_edges_id'), 'edges', ['id'], unique=False)
    op.create_table('graphs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('graphs_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name='graphs_note_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='graphs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_graphs_id'), 'graphs', ['id'], unique=False)
    op.create_table('ambiguities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('graph_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.id'], name=op.f('ambiguities_graph_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ambiguities_pkey'))
    )
    op.create_index(op.f('ix_ambiguities_id'), 'ambiguities', ['id'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('graph_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.id'], name=op.f('nodes_graph_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('nodes_pkey'))
    )
    op.create_index(op.f('ix_nodes_id'), 'nodes', ['id'], unique=False)
    # ### end Alembic commands ###
